apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  automountServiceAccountToken: false
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP