kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-retain
provisioner: kubernetes.io/azure-disk  # Azure Disk, not Azure Files
reclaimPolicy: Retain # default storage classes delete the Azure disk/file when PV is deleted
parameters:
  storageaccounttype: Premium_LRS # use premium SSD
  kind: Managed