apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /mydata
          name: data
    - name: other
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /mydata
          name: data
  volumes:
    - name: data
      emptyDir: {}
        